### PR TITLE
Case insensitive keywords

### PR DESCRIPTION
**Pull request by AliHaider93**
The keywords in .k file are case insensitive.

### CODE REVIEW

**Comment by drossberg** [comment]
Would be "Node" be a valid keyword too? In this case, using `toupper()` would be better.

**Comment by drossberg** [comment]
Or something similar, see e.g. the Notes in https://en.cppreference.com/w/cpp/string/byte/toupper.

**Comment by AliHaider93** [comment]
> Would be "Node" be a valid keyword too? In this case, using `toupper()` would be better.

your guess is right :), Node Also works, also NOde works, I will use toupper().

**Comment by AliHaider93** [comment]
I tried using special characters for the part name like 
image
image
and LS-PrePost doesnt care about them, so I think to upper is sfficent with a condition to change the parts names into a sequence of numbers if toupper()  incounters special charachters.

**Comment by AliHaider93** [comment]
it's unnessessary to check for weird Part name, mged doesn't care about it 
image

**Comment by drossberg** [comment]
`toupper()` is applied to the first token of lines starting with a '*' only, right? Therefore, other stuff, like the part names, aren't touched.

**Comment by drossberg** [comment]
Very nice patch. In fact, it could  be a one-liner too.

**Pull request merged**
