### PR TITLE
Nurbs editing Milestone 1

### PR DESCRIPTION
**Pull request by GregoryLi0**
Milestone 1: Perform simple operations on brep geometries using command line.
**Curve operations**:
- create (using a pre-determined template)
- in (given detailed description)
- move
- set control vertex
- flip
- insert knot
- trim
- join (join end of curve 1 to start of curve 2)

**Surface operations**:
- create (using a pre-determined template)
- create from curves (create a surface between two curves)
- move
- set control vertex
- trim

### CODE REVIEW

**Comment by drossberg** [comment]
Hi Gregory, thanks for providing this patch.

However, the first thing I'm doing, when proofreading a patch, is checking if it conforms to our coding style. The guidelines are written in the HACKING file in the root directory of the brlcad sources. Please, read the CODING STYLE & STANDARDS section there, especially "1) Indentation whitespace" and "3) Braces".

Please change your code accordingly and update your pull request.

**Comment by GregoryLi0** [comment]
Hi Daniel, I have checked my coding style according to HACKING. Please review my pull requests.
I have changed the command of "brep .. surface create_from_curves" to "brep .. surface birail". So the test shell script shall be modified, too.

**Comment by drossberg** [comment]
Stylistic issues:
- The year in the header of the new files (edit.h, edit.cpp, curve.cpp, surface.cpp) should be the year of their creation only.
- Source files should end with a new-line (edit.cpp, sourface.cpp).
- Aim for consistent spacing (e.g. edit.h, line 148).

In addition:
- The `extern "C"` in the src/libged/brep brep.cpp, curve.cpp, and surface.cpp files shouldn't be necessary. In fact, you can make them static. These functions are used in these files only.
- edit.cpp, line 44: What do you mean with `if (position)`? `position` is a reference, not a pointer, i.e. always there, or?

**Comment by GregoryLi0** [comment]
Thank you for such a meticulous review! I understand these practices and have made modifications.

**Pull request merged**
