### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -L acount,aray,ba,childs,comando,desig,fo,mater,nd,ocur,pard,survice`

### CODE REVIEW

**Comment by brlcad** [comment]
Hi @luzpaz this looks really impressive, but it can't be applied as-is since you've included modifications to 3rd party codes that are merely co-located in our repository for compilation, and are not ours to modify.  Can you exclude all of src/other and misc/tools?  That will make this a lot easier to review...

**Comment by brlcad** [comment]
Others to exclude include:
doc/docbook/resources/other/docbook5xi.rnc
misc/  (all of it, not just misc/tools)

**Comment by luzpaz** [comment]
@brlcad please recheck

**Comment by brlcad** [comment]
@luzpaz This looks great, thank you!  I'm half-surprised you found as many as you did.  We've had a few devs over the years obsess over spelling.  The ones you found may have been introduced in the past couple years.  I've credited you in our AUTHORS file as Luz Paz <luzpaz>, but let me know if there's another name you'd prefer.

I see from your commit history that you're really good at doing spelling fixes for folks.  Have you considered trying to automate it?  Either on a case-by-case basis, like helping us create a regression test that detects / prevents new mistakes, or across a set of projects where you scan and submit PRs periodically?

**Comment by luzpaz** [comment]
@brlcad I'm happy to do it. You would be surprised at the amount of bugs that have been solved by doing a deeper spell check. I use a combination of [`codespell`](https://github.com/codespell-project/codespell) and vscode regex-fu to run these analyses. As for automation, it's pretty simple to set up a GH action. Just 2 files are needed

`.github/workflows/codespell.yml`
`.github/codespellignore`

Here's how FreeCAD did it:
https://github.com/FreeCAD/FreeCAD/commit/c7cf9b25dfc6ec4fbbba8db7adfd7eb54be105fa

As for automating PRs across several projects, that could be out of my coding scope + codespell does give a number of false positives because it's still a WIP itself. Last thing I want to do is irritate FLOSS devs that are (already) overworked etc...by submitting yet another PR that would not be necessary for them to review. Some devs think spelling for source comments is trivial or that these types of PRs are motivated by an agenda for notoriety. Anyway, like I said, I'm happy to do it as a contribution to FLOSS.

**Pull request merged**
